
# A minimal left prompt

format = '''$all$os $directory$git_branch$git_commit$git_state$git_metrics$git_status 
$character'''

right_format = '''$username$hostname$localip$custom'''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

[username]
style_user = 'purple'
style_root = 'red bold'
format = '[$user@]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](purple)[ $ssh_symbol](bold)'
ssh_symbol = ''
disabled = false

[os]
format = "[$symbol]($style)"
style = "bold"
disabled = false

[os.symbols]
Arch = "󰣇"
Ubuntu = ""

[python]
disabled = true

[localip]
ssh_only = false
format = " [$localipv4](purple)"
disabled = false

[custom.proxyip]
command = 'echo $HTTP_PROXY | rev | cut -d"/" -f1 | rev'
when = ''' test -n "$HTTP_PROXY" '''
format = '  [$output]()'
